IMG_TYPES = [
    {"name": "biryani", "num": 81},
    {"name": "burger", "num": 87},
    {"name": "butter-chicken", "num": 22},
    {"name": "dessert", "num": 36},
    {"name": "dosa", "num": 83},
    {"name": "idly", "num": 77},
    {"name": "pasta", "num": 34},
    {"name": "pizza", "num": 95},
    {"name": "rice", "num": 35},
    {"name": "samosa", "num": 22},
]
FOOD_NAMES = [
    {"type": "Pork", "names": ["Bacon", "Ham"]},
    {"type": "Beef", "names": ["Wagyu", "Steak"]},
    {"type": "Donuts", "names": ["Maple", "Chocolate", "Donut Holes"]},
    {
        "type": "Dumplings",
        "names": ["Arepa", "Fun guo", "Har gow", "Pierogi", "Wonton"],
    },
    {
        "type": "Pizza",
        "names": ["Pepperoni", "Hawaiian", "Margherita", "Sausage", "Cheese"],
    },
    {
        "type": "Ice cream",
        "names": [
            "Chocolate",
            "Vanilla",
            "Cookies and cream",
            "Mint chocolate",
            "Rocky Road",
        ],
    },
    {
        "type": "Pasta",
        "names": [
            "Lasagna",
            "Linguini",
            "Ravioli",
            "Carbonara",
            "Bolognese",
            "Spaghetti",
        ],
    },
    {
        "type": "Poultry",
        "names": [
            "Buffalo wing",
            "Chicken balls",
            "Chicken nuggets",
            "Chicken steak",
            "Chicken feet",
        ],
    },
    {
        "type": "Seafood",
        "names": [
            "Crappit heid",
            "Croquette",
            "Curanto",
            "Dressed herring",
            "Fish and chips",
            "Fish ball",
            "Fish chowder",
        ],
    },
]
REST_NAMES = [
    {
        "type": "Seafood",
        "names": [
            "Sam’s Shrimp Shack",
            "Codfather Burgers & Sandwiches",
            "Tiderock Cafe",
            "Five Sails Restaurant",
            "Surf’s Up Bistro",
            "The Captain’s Boil",
            "Mermaid Cocktail House",
            "La Mar",
            "Tidal Bore Brewpub",
            "Neptune Oyster",
            "Sandy Point Grill",
            "Mama’s Fish House",
            "Clamshell Cafe",
            "Pelican Pier",
        ],
    },
    {
        "type": "Pizza",
        "names": [
            "Pinnacle Pizzeria",
            "Una Pizza Napoletana",
            "The Sassy Slice",
            "Pomo",
            "Escape to Italy Pizzeria",
            "Brick Fire Tavern",
            "Cheese Please Pizza",
            "Il Forno",
            "Cindy’s Cucina",
            "La Leggenda Pizzeria",
            "Mozza Heaven Pizza",
            "Flour House",
            "Angie’s Artisan Pizza",
            "Basil & Barley Pizzeria",
        ],
    },
    {
        "type": "Italian",
        "names": [
            "Pezzo Perfetto",
            "Al Di La Trattoria",
            "Il Pesce House",
            "Frasca Food and Wine",
            "Guiliana’s Grande Ristorante",
            "Osteria Mozza",
            "Radunare Wine Bar",
            "Mercato Mission",
            "Nonna’s Garden Ristorante",
            "Ask for Luigi",
            "Sofia’s Pasta House",
            "Eataly",
            "Festa Grande Ristorante",
            "Toscana Italian Grill",
        ],
    },
    {
        "type": "Bakery",
        "names": [
            "CinnaMan’s Café ",
            "The Uprising Craft Bakery",
            "Frosty Favorites",
            "Bunnie Cakes",
            "A Dash of Sweet Bakery",
            "Crumbl Cookies",
            "Mindy’s Muffins",
            "Prairie Boy Bread",
            "Butter Galore",
            "Flour Child Bakery & Cafe",
            "Sans Gluten Bakery",
            "Mad Batter Bakers",
            "George’s Ginger Emporium",
            "Bakeology Cafe & Bakery",
        ],
    },
]
DESC = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan lorem metus, non accumsan elit ornare eget. Integer quis nibh mi. Curabitur ut mattis sem, a condimentum arcu. Maecenas laoreet, risus ac porttitor tincidunt, nibh risus auctor massa, at rhoncus mauris dui vel ligula. In luctus eget nulla vitae sodales. Praesent vulputate leo id lacus accumsan, et ultrices sem sollicitudin. Integer auctor ac nibh id maximus. Sed nibh diam, sodales non neque vel, fringilla blandit elit. Nam ante nunc, malesuada in tortor quis, tempor varius ipsum. Nam nec nunc sit amet justo viverra pulvinar. Quisque sit amet nulla eu libero pharetra placerat nec eu erat. Sed mollis, nisl vel congue tempor, nisl ante elementum sem, non aliquam felis elit vitae urna. Donec ac nulla luctus, finibus ligula sit amet, aliquam sapien."
